# pull the official base image
FROM node:alpine AS development

ENV NODE_ENV development

# set working direction
WORKDIR /app
# install application dependencies
COPY package.json .
COPY package-lock.json .
RUN npm i
# add app
COPY . .

EXPOSE 3000

# start app
CMD ["npm", "start"]